### ISSUE TITLE
Payment confirmation status - 403 Forbidden

### ISSUE THREAD

**Issue by maltitco** [mirumee/saleor#1868]
I check the operation of dotpay payments from the django-payments package.
I have already eliminated most errors, but I receive now 403 Forbidden for the payment status.

After the payment process, the operator sends information about the payment status to the store:

<img width="573" alt="zrzut ekranu 2018-03-05 o 10 35 19" src="https://user-images.githubusercontent.com/1561204/36967776-f850533a-2060-11e8-8cd5-63ee42fa99be.png">

Where should I look for a solution?

**Comment by rafalp** [comment]
Hey @maltitco, could you please tell us which version of Saleor are you using?

We've had [nasty regression](https://github.com/mirumee/saleor/issues/1872) happen on master branch few days ago that we've fixed around the time of your report, and I'm wondering those errors you are seeing were also caused by it. 🤔

**Comment by NyanKiyoshi** [comment]
From django-payment source code, it looks like [the received data is not valid](
https://github.com/mirumee/django-payments/blob/db6279d220085f83f3c85b46b12d46aa871c5433/payments/dotpay/__init__.py#L64-L68).

```python
    def process_data(self, payment, request):
        form = ProcessPaymentForm(payment=payment, pin=self.pin,
                                  data=request.POST or None)
        if not form.is_valid():
            return HttpResponseForbidden('FAILED')  # <-- Raises 403 here
```

Could you show us the received data? (`request.POST`) That could probably help us (hide any sensitive data).

Meanwhile, I will try to reproduce this locally ASAP.

**Comment by maltitco** [comment]
@NyanKiyoshi you can create a test account: https://ssl.dotpay.pl/test_seller/test/registration/

**Comment by NyanKiyoshi** [comment]
@maltitco thank you for that link! Can you try to set the dotpay API version to legacy? The dev version raises a 403 on saleor (didn't look yet).

You can change the version from your dotpay account: **Settings →  Shop configuration → Edit shop configuration → Payment api version → Legacy**.

You may also run into those errors:

```
ERROR celery.app.trace Task saleor.order.emails.send_order_confirmation[f97c2947-b2b0-4e79-a69a-d1a2feddb3c4] raised unexpected: TemplateSyntaxError("'gross' is not a valid tag or filter in tag library 'prices_i18n'",) [PID:22486:Thread-161]
Traceback (most recent call last):
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/sayuri/development/saleor_forked/saleor/order/emails.py", line 44, in send_order_confirmation
    _send_confirmation(**email_data)
  File "/home/sayuri/development/saleor_forked/saleor/order/emails.py", line 28, in _send_confirmation
    template_name=template)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/templated_email/__init__.py", line 70, in send_templated_mail
    headers=headers, create_link=create_link, **kwargs)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/templated_email/backends/vanilla_django.py", line 258, in send
    create_link=create_link)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/templated_email/backends/vanilla_django.py", line 134, in get_email_message
    template_suffix or file_extension)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/templated_email/backends/vanilla_django.py", line 106, in _render_email
    response[part] = render_block_to_string(full_template_names, part, render_context)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/render_block/base.py", line 39, in render_block_to_string
    return django_render_block(t, block_name, context)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/render_block/django.py", line 27, in django_render_block
    return _render_template_block(template, block_name, context_instance)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/render_block/django.py", line 70, in _render_template_block
    return _render_template_block_nodelist(template.nodelist, block_name, context)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/render_block/django.py", line 85, in _render_template_block_nodelist
    return node.render(context)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/django/template/loader_tags.py", line 182, in render
    template = context.template.engine.get_template(template_name)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/django/template/defaulttags.py", line 1077, in load
    subset = load_from_library(lib, name, bits[1:-2])
  File "/home/sayuri/_py3vene/lib/python3.6/site-packages/django/template/defaulttags.py", line 1050, in load_from_library
    name, label,
django.template.exceptions.TemplateSyntaxError: 'gross' is not a valid tag or filter in tag library 'prices_i18n'
ERROR saleor.order.signals Recording order in analytics failed [PID:22486:Thread-161]
Traceback (most recent call last):
  File "/home/sayuri/development/saleor_forked/saleor/order/signals.py", line 20, in order_status_change
    analytics.report_order(order.tracking_client_id, order)
  File "/home/sayuri/development/saleor_forked/saleor/core/analytics.py", line 55, in report_order
    for ol in group]
  File "/home/sayuri/development/saleor_forked/saleor/core/analytics.py", line 55, in <listcomp>
    for ol in group]
AttributeError: 'OrderLine' object has no attribute 'get_price_per_item'
ERROR saleor.order.signals Recording order in analytics failed [PID:22486:Thread-161]
Traceback (most recent call last):
  File "/home/sayuri/development/saleor_forked/saleor/order/signals.py", line 20, in order_status_change
    analytics.report_order(order.tracking_client_id, order)
  File "/home/sayuri/development/saleor_forked/saleor/core/analytics.py", line 55, in report_order
    for ol in group]
  File "/home/sayuri/development/saleor_forked/saleor/core/analytics.py", line 55, in <listcomp>
    for ol in group]
AttributeError: 'OrderLine' object has no attribute 'get_price_per_item'
```

If you run into those errors, please try to downgrade to the January release of Saleor (or around 570a8dd46bdb56cbca952a41d422966a1372d44d). Those bugs were introduced recently due to a big revamp, it was fixed but not merged as I write this.

Meanwhile I will downgrade and try to see what's wrong with the dev version.

**Comment by maltitco** [comment]
@NyanKiyoshi I tested payments with setting api in legacy mode and works correctly, there was no need to downgrade.

I checked what is in the dotpay documentation regarding the api configuration, there is information that the payment should contain with the parameter `api_version=dev`. I added it to `get_hidden_fields` `in __init__.py` it is passed correctly but there is still an error 403.

**Comment by NyanKiyoshi** [comment]
(ping @elwoodxblues, so you can maybe open an issue in django-payments as we spoke!)

**Comment by elwoodxblues** [comment]
I've released a [new version of django-payments](https://github.com/mirumee/django-payments/releases/tag/0.12.2) which updates the Dotpay integration. 403 error may be also related to the Saleor's success callback being protected by CSRF. Issue #1987 contains more details about the problem and the possible solution.
