### ISSUE TITLE
Error on initial migrate

### ISSUE THREAD

**Issue by myulz** [mirumee/saleor#550]
Hi, can anyone help me solve this error I ran into when trying to run 'migrate.py' for the first time? I couldn't find any issues that already covered this and I only see 'userprofile.User' once, in 'settings.py'

<code>
SystemCheckError: System check identified some issues:

CRITICALS:

userprofile.User: (auth.C009) <class 'saleor.userprofile.models.User'>.is_anonymous must be an attribute or property rather than a method. Ignoring this is a security issue as anonymous users will be treated as authenticated!

userprofile.User: (auth.C010) <class 'saleor.userprofile.models.User'>.is_authenticated must be an attribute or property rather than a method. Ignoring this is a security issue as anonymous users will be treated as authenticated!</code>

There doesn't seem to be a way to ignore the SystemCheckError and continue :(

Thank you!!

**Comment by codeguruji** [comment]
I am facing with the same issue.

**Comment by jaibuu** [comment]
Same here, is there a demo site one could try before working around this issue?

**Comment by codeguruji** [comment]
there is no demo site

**Comment by krzysztofwolski** [comment]
Hey, I need to know more how to reproduce this error
1. Could you give me more information about your configuration? OS, Python and Django versions?
1. Did you used official installation guide? https://saleor.readthedocs.io/en/latest/installation.html
1. Have you tried docker image? It was easiest way for me to test Saleor

**Comment by nidico** [comment]
I am also facing this issue.

> 1. Could you give me more information about your configuration? OS, Python and Django versions?

Ubuntu 16.04, Python 3.5.2, Django 1.10 according to `requirements.txt`.

> 2. Did you used official installation guide? https://saleor.readthedocs.io/en/latest/installation.html

Yes. Apart from having installed `wheel` locally in addition (see #552).

> 3. Have you tried docker image? It was easiest way for me to test Saleor

Not tried, want to have a development environment without dealing with docker.

**Comment by myulz** [comment]
OSX El Capitan/Yes, I used the official installation guide/ Python 3.5.2,Django 1.10

Thanks for helping us!

**Comment by codeguruji** [comment]
You can try deploying on heroku to reproduce this error.

**Comment by krzysztofwolski** [comment]
You're right - there is problem with django version in requirements.txt. Thanks for reporting it! :)
Fast fix for testing - ```pip install -U django==1.9```.

**Comment by patrys** [comment]
Thank you for reporting this. It seems Django has recently implemented a new system check that was not in place when we conducted initial testing. This is now fixed on `master`.

**Comment by nidico** [comment]
Fix confirmed.

**Comment by myulz** [comment]
@patrys 
django 1.10 also causes an error after clicking 'Place Order'.

<code>Exception Type: TypeError at /checkout/summary/
Exception Value: 'shipping_required' is an invalid keyword argument for this function</code>

Everything is working fine for me after downgrading to Django 1.9

**Comment by patrys** [comment]
@myulz could you provide a complete stack trace? I've updated dependencies on `master` branch and "Place order" seems to work fine (Python 3.5, Django 1.10).

**Comment by myulz** [comment]
@pastrys I updated my fork with master after your latest dependency update and I still get the same error on 1.10

<code>

Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/checkout/summary/

Django Version: 1.10
Python Version: 3.5.2
Installed Applications:
['storages',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sitemaps',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.auth',
 'saleor.userprofile',
 'saleor.discount',
 'saleor.product',
 'saleor.cart',
 'saleor.checkout',
 'saleor.core',
 'saleor.order',
 'saleor.registration',
 'saleor.dashboard',
 'saleor.shipping',
 'versatileimagefield',
 'babeldjango',
 'bootstrap3',
 'django_prices',
 'emailit',
 'mptt',
 'payments',
 'selectable',
 'materializecssform',
 'rest_framework',
 'webpack_loader']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'babeldjango.middleware.LocaleMiddleware',
 'saleor.cart.middleware.CartMiddleware',
 'saleor.core.middleware.DiscountMiddleware',
 'saleor.core.middleware.GoogleAnalytics',
 'saleor.core.middleware.CountryMiddleware',
 'saleor.core.middleware.CurrencyMiddleware']



Traceback:

File "/Users/Myles/saleor/env/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/Users/Myles/saleor/env/lib/python3.5/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/Users/Myles/saleor/env/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/Users/Myles/saleor/env/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/Myles/saleor/saleor/checkout/core.py" in func
  301.         response = view(request, checkout)

File "/Users/Myles/saleor/saleor/checkout/views/validators.py" in func
  11.             return view(request, checkout)

File "/Users/Myles/saleor/saleor/checkout/views/discount.py" in func
  29.         response = view(request, checkout)

File "/Users/Myles/saleor/saleor/checkout/views/__init__.py" in summary_view
  50.         return view(request, checkout)

File "/Users/Myles/saleor/saleor/checkout/views/validators.py" in func
  35.         return view(request, checkout)

File "/Users/Myles/saleor/saleor/checkout/views/validators.py" in func
  26.         return view(request, checkout)

File "/Users/Myles/saleor/saleor/checkout/views/summary.py" in summary_with_shipping_view
  59.         order = create_order(checkout)

File "/Users/Myles/saleor/saleor/checkout/views/summary.py" in create_order
  11.     order = checkout.create_order()

File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py" in inner
  30.                 return func(*args, **kwds)

File "/Users/Myles/saleor/saleor/checkout/core.py" in create_order
  235.                 shipping_method_name=shipping_method_name)

File "/Users/Myles/saleor/env/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py" in create
  609.             return super(RelatedManager, self.db_manager(db)).create(**kwargs)

File "/Users/Myles/saleor/env/lib/python3.5/site-packages/django/db/models/manager.py" in manager_method
  85.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/Users/Myles/saleor/env/lib/python3.5/site-packages/django/db/models/query.py" in create
  397.         obj = self.model(**kwargs)

File "/Users/Myles/saleor/env/lib/python3.5/site-packages/django/db/models/base.py" in __init__
  555.                 raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])

Exception Type: TypeError at /checkout/summary/
Exception Value: 'shipping_required' is an invalid keyword argument for this function

</code>
http://dpaste.com/08QYX1Q

**Comment by patrys** [comment]
@myulz Good catch, it turns out that under certain circumstances we tried to pass a non-existent field name to `manager.create()`. Not sure how and why it worked in Django 1.9 though.

Should be fixed now.
